name: flutter_web_auth_2_windows
description: Windows implementation of the flutter_web_auth_2 plugin platform interface.
version: 1.1.2
homepage: https://github.com/ThexXTURBOXx/flutter_web_auth_2
repository: https://github.com/ThexXTURBOXx/flutter_web_auth_2
issue_tracker: https://github.com/ThexXTURBOXx/flutter_web_auth_2/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: flutter_web_auth_2
    platforms:
      windows:
        dartPluginClass: FlutterWebAuth2Windows
        pluginClass: none

dependencies:
  ffi: ">=1.1.2 <3.0.0"
  flutter:
    sdk: flutter
  flutter_web_auth_2_platform_interface: ^1.1.2
  url_launcher: ^6.1.5
  win32: ">=2.7.0 <4.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1
